name: VUnit Action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Check workspace
        run: pwd
      - name: Run VUnit tests
        uses: VUnit/vunit_action@v0.1.0
        with:
          cmd: scriptrun.py
      - name: Check workspace
        run: pwd
