name: VUnit Action
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check workspace
        run: pwd
      - uses: VUnit/vunit_action@master
        with:
          working-directory: seg7_display_driver_ib
          cmd: script/run.py
      - name: Check workspace
        run: pwd
