name: VUnit Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check workspace
        run: ls
      - uses: VUnit/vunit_action@v0.1.0
        with:
          working-directory: seq7_display_driver_lib
          run_file: script/run.py
